package com.revature.models;

import java.time.LocalDate;

public class User {
	
	private int id;
	private String name;
	private String jobTitle;
	private LocalDate hireDate;
	
	public User() {
		super();
	}

	public User(int id, String name, String jobTitle, LocalDate hireDate) {
		super();
		this.id = id;
		this.name = name;
		this.jobTitle = jobTitle;
		this.hireDate = hireDate;
	}

	//this last constructor will be used to create new records in our database
	//because this constructor will take all needed fields to create a new user minus the id (autogenerated in DB)
	public User(String name, String jobTitle, LocalDate hireDate) {
		super();
		this.name = name;
		this.jobTitle = jobTitle;
		this.hireDate = hireDate;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public LocalDate getHireDate() {
		return hireDate;
	}

	public void setHireDate(LocalDate hireDate) {
		this.hireDate = hireDate;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", jobTitle=" + jobTitle + ", hireDate=" + hireDate + "]";
	}
}
